---
- name: Install docker and pip for ansible management
  pacman: name={{item}}
  with_items:
       - docker
       - python2-pip
       - python2

- name: install pip packages for ansible
  pip: name= "{{ item }}" executable=/usr/bin/pip2
  become: true
  pip: name={{ item }}
  with_items:
    - setuptools
    - docker-py

- name: install docker-gen
  unarchive:
    src: https://github.com/jwilder/docker-gen/releases/download/0.7.3/docker-gen-linux-amd64-0.7.3.tar.gz
    dest: /usr/local/bin/
    remote_src: True
